plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs9.github.io
baseurl: "/s24-swsolis"

course: "CS 9"
qtr: "S24"
instructor: "Sharon Solis" 
quarter: "Spring 2024"
piazza_url: https://piazza.com/ucsb/spring2024/cmpsc9/home
gauchospace_course_page:
lecture_recordings: https://gauchocast.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=0a1305b2-d90d-4a41-885a-b14c01652083
gradescope_class_url: https://www.gradescope.com/courses/760444

github_url: https://github.com/ucsb-cs9/s24-swsolis

start_week: 1
start_date: 2024-03-31 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true

# ### https://registrar.sa.ucsb.edu/calendars/calendars-deadlines/academic-calendars
# ### https://registrar.sa.ucsb.edu/calendars/calendars-deadlines/registration-pass-dates

cal_dates: >                                                                    
  [                                                                            
    {"label":"S24 1st day of instruction", "date":"2024-04-01" },
    {"label":"Academic Integrity Contract Due", "date":"2024-04-09" },
    {"label":"S24 deadline to drop courses", "date":"2024-04-26" },
    {"label":"S24 CS 9 MIDTERM (12:30pm - 1:45pm)", "date":"2024-05-02" },
    {"label":"Holiday: Memorial Day", "date":"2024-05-27" },
    {"label":"S24 instruction ends", "date":"2024-06-07" },
    {"label":"S24 CS 9 FINAL (12:00pm - 3:00pm)", "date":"2024-06-10" },                                                
    {"label":"S24 qtr ends", "date":"2024-06-14" }                              
  ]

kramdown:
   parse_block_html: true
   default_lang: cpp

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
